version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto
    ports: 
      - 1883:2883
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
